### ISSUE TITLE
Upgrade to the new version of Jupyter Book

### ISSUE THREAD

**Issue by choldgraf** [ds-modules/curriculum-guide#11]
### Description

The version of the content in this repository is from a very old version of Jupyter Book. We should upgrade the content and structure to the new version documented at jupyterbook.org

### Benefit

This will make it much easier to update and maintain our content, and get new features from Jupyter Book!

### Implementation

The easiest thing to do is probably the following:

1. Create a new branch called `new-book`
2. Delete everything except for `_data` (because it's our TOC), `content/` (because it's our content), and `_config` (because that will help us create a new config)
3. Follow the instructions at jupyterbook.org to create a new book from scratch, **migrating over** the old TOC and configuration to the new book's syntax
4. You might also need to update the `requirements` file to ensure that the book builds properly with CI/CD. You should look into using `readthedocs` or `github-pages` to host the book online - see https://jupyterbook.org/publish/web.html)
4. Once the new book is building ~ the same way, then we are ready to update the `master` brach.
5. The easiest next step is to **delete** the master branch (since it has a ton of old files), **rename** our new book branch to `main`, and then make this the default branch.

At that point, we should have a new jupyter book structure running on the `main` branch and building with GitHub Pages.

**Comment by balajialg** [comment]
@choldgraf Thank you so much for the detailed documentation. I tried building the page after removing the files required for the older version of Jupyter Books. I am getting the following error,

![image](https://user-images.githubusercontent.com/2306166/132425973-540d131e-b833-4260-a827-0292bd8f18ac.png)

![image](https://user-images.githubusercontent.com/2306166/132426036-f4fbc272-f773-4606-b23a-44c35a569a0b.png)

Any inputs on how to resolve this error?

**Comment by balajialg** [comment]
Not sure whether [this issue](https://github.com/executablebooks/jupyter-book/issues/964) is relevant to the one that I have currently!

**Comment by choldgraf** [comment]
Hmmm which branch are you on? Could you provide a link to the current file structure?

**Comment by balajialg** [comment]
@choldgraf I am on the upgrade branch. [Link ](https://github.com/balajialg/curriculum-guide/tree/upgradebranch)to the existing file structure!

**Comment by balajialg** [comment]
@choldgraf Sorry for following up again! Jupyter books version for this repo is 0.6.3. Unfortunately, the [migration script](https://jupyterbook.org/customize/toc.html?highlight=migrate) offered as part of this documentation seems not to work for this version. Jonathan and I spent a significant amount of time on Friday looking for options to make this script work, but we didn't find any better alternatives. What do you think is the best way to seek help for this issue? Should I post it in the Jupyter-books repo or does posting here itself work?

I have exhausted all my options, and the only feasible option other than seeking your help seems to move this upgrade to the backlog. Please let me know if you can help. Thanks, and I appreciate your patience.

**Comment by choldgraf** [comment]
hey - I've pushed to your update branch a fix that should resolve this. The problem was that there was a file about git that was completely empty, and this was creating the confusing error. I also removed the `_build` folder from the commit history and added a rule to ignore it, since that's not something you want to commit to the source repository

**Comment by balajialg** [comment]
Thanks a ton @choldgraf! Really appreciate it. I will fix the remaining errors and make the final push to this repository.

**Comment by balajialg** [comment]
@choldgraf Based on your inputs, I was able to build the new TOC file and publish changes to a [dummy site](https://balajialg.github.io/curriculum-guide/intro.html) I had created for now! However, all the toc files are not getting referenced on this website. Any inputs/guidelines? Sharing the new toc file for your reference,

```
format: jb-book
root: intro
title: Home
chapters:
- file: connector/general/what-is-a-connector
  title: What is a Connector course?
  sections:
  - file: connector/general/previous-connectors
    title: Previous Connectors
  - file: module/general/what-is-a-module
    title: What is a Data Science Module?
  - file: dec/general/what-is-a-data-enabled-course
    title: What is a Data-Enabled Course?
  - file: technology/pedagogy-and-technology
    title: Pedagogy and Technology
  sections:
  - file: technology/pedagogy-and-technology/introduction-to-jupyter
    title: Introduction to Jupyter
  - file: technology/pedagogy-and-technology/notebook-zero
    title: Notebook Zero
  - file: technology/r-datahub
    title: R DataHub
  sections:
 # title: Creating a Connector
  - file: connector/instructor/logistics
    title: Logistics, Rooms, and Technology
  - file: connector/instructor/syllabus-design
    title: Designing Your Syllabus
  - file: connector/instructor/student-help
    title: Requesting Student Help
  - file: connector/instructor/communication-channels
    title: Joining Communication Channels
  - file:  connector/instructor/checklist
    title: Pre-Semester Checklist
  sections:
          #title: Creating a Connector
  - file: module/instructor/preplanning
    title: Pre-Planning
  - file: module/instructor/develop
    title: Developing the Module
  - file: module/instructor/deploy-help
    title: Requesting Deployment Help
  # Workflow Basics
  sections:
  - file: workflow/creating-notebooks
    title: Creating Assignments
  - file: workflow/pushing-to-github
    title: Uploading Files to Github
  - file: workflow/distributing-notebooks
    title: Distributing Assignments
  - file: workflow/collecting-grading-assignments
    title: Collecting and Grading Assignments
 # During the Course
  sections:
  - file: technology/jupyter/large-datasets
    title: Working with Large Datasets
  - file: technology/jupyter/python-packages
    title: Using Additional Python Packages
  - file: faq/jupyterhub-intro
    title: FAQ's to set up JupyterHub
    sections:
    - file: faq/onboarding
    - file: faq/changerequirements
    - file: faq/admin
    - file: faq/troubleshoot
    - file: technology/jupyter/fixing-errors
      title: JupyterHub Frequently Asked Questions
    - file: faq/features
    - file: faq/share
    - file: technology/resources
      title: Resources for Students
  # Reference
    sections:
    - file: general/people
      title: People
    - file: general/terms-and-abbreviations
      title: Terms and Abbreviations
    - file: general/contact
      title: Contact
```
